import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato, Quicksand } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const latoFont = Lato({
  weight: ['400', '700'],
  subsets: ["latin"],
  variable: "--font-lato"
});

const quickSandFont = Quicksand({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: "--font-quickSand"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${latoFont.variable} ${quickSandFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
