import type { Metadata } from "next";
import { Geist, Geist_Mono, Unbounded, Figtree } from "next/font/google";
import "./globals.css";
import style from "./style.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const unBoundedFont = Unbounded({
  subsets: ['vietnamese'],
  variable: "--font-unbounded",
  weight: ['400', '700']
});

const figTree = Figtree({
  subsets: ['latin-ext'],
  variable: "--font-figTree",
  weight: ['400', '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${style.body} ${geistSans.variable} ${figTree.variable} ${unBoundedFont.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
